###################
### KEYBINDINGS ###
###################

$fileManager = kitty -e yazi
$terminal = kitty
$menu = rofi -show drun
$mainMod = SUPER 

bind = $mainMod, T, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, exec, firefox
bind = $mainMod, SPACE, togglefloating,
bind = $mainMod, D, exec, $menu
bind = $mainMod, J, layoutmsg, togglesplit # dwindle
bind = $mainMod, L, movefocus, l
bind = $mainMod, APOSTROPHE, movefocus, r
bind = $mainMod, P, movefocus, u
bind = $mainMod, SEMICOLON, movefocus, d
bind = $mainMod SHIFT, L, movewindow, l
bind = $mainMod SHIFT, APOSTROPHE, movewindow, r
bind = $mainMod SHIFT, P, movewindow, u
bind = $mainMod SHIFT, SEMICOLON, movewindow, d
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
