source = ~/.config/hypr/binds.conf

################
### MONITORS ###
################

monitor=DP-2, 1920x1080@165, 0x0, 1

###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun

#################
### AUTOSTART ###
#################

exec-once = swaybg -i ~/kaif.jpg -m fill

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = HYPRCURSOR_THEME,Obsidian
env = XCURSOR_THEME,Obsidian

###################
### PERMISSIONS ###
###################

ecosystem:enforce_permissions = true

#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 4
    gaps_out = 4
    border_size = 2
    col.active_border = rgb(ded0db)
    col.inactive_border = rgb(1a1a1a)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

cursor {
    no_hardware_cursors = true
}

decoration {
    rounding = 4
    active_opacity = 1.0
    inactive_opacity = 1.0
    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

animations {
    enabled = yes, please :)

    bezier = hisBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, hisBezier, popin 80%
    animation = windowsOut, 1, 5, hisBezier, popin 80%
    animation = layers, 1, 5, hisBezier, fade
    animation = layersIn, 1, 5, hisBezier, fade
    animation = layersOut, 1, 5, hisBezier, fade
    animation = fade, 1, 5, hisBezier
    animation = workspaces, 1, 5, hisBezier, slide
    animation = specialWorkspaceIn, 1, 5, hisBezier, fade
    animation = specialWorkspaceOut, 1, 5, hisBezier, fade
}

dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = master
}

#############
### INPUT ###
#############

input {
    kb_layout = us, ru
    follow_mouse = 1
    kb_options = grp:alt_shift_toggle
    sensitivity = 0.25
    left_handed = true
    accel_profile = flat
}

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
