#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 4
    gaps_out = 4
    border_size = 2
    col.active_border = rgba(ffffff80)
    col.inactive_border = rgba(00000080)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 4
    active_opacity = 0.95
    inactive_opacity = 0.85
    shadow {
        enabled = false
    }
    blur {
      enabled = true
      xray = false
      special = false
      new_optimizations = true
      size = 8
      passes = 3
      brightness = 1
      noise = 0.05
      contrast = 0.89
      popups = true
      popups_ignorealpha = 0.6
      input_methods = true
      input_methods_ignorealpha = 0.8
      ignore_opacity = true
    }
}
#Rule to blur quickshell bar
layerrule = blur on, match:namespace bar
#Rule to blur rofi
layerrule = blur on, match:namespace rofi

animations {
    enabled = yes, please :)

    bezier = hisBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 5, hisBezier, popin 80%
    animation = windowsOut, 1, 5, hisBezier, popin 80%
    animation = layers, 1, 5, hisBezier, fade
    animation = layersIn, 1, 5, hisBezier, fade
    animation = layersOut, 1, 5, hisBezier, fade
    animation = fade, 1, 5, hisBezier
    animation = workspaces, 1, 5, hisBezier, slide
    animation = specialWorkspaceIn, 1, 5, hisBezier, fade
    animation = specialWorkspaceOut, 1, 5, hisBezier, fade
}

dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    new_status = master
}
