#################
### AUTOSTART ###
#################

exec-once = qs -p $HOME/.config/quickshell/lockscreen/shell.qml
exec-once = awww-daemon && awww restore
exec-once = quickshell
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
