##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

#windowrule {
#    # Fix some dragging issues with XWayland
#    name = fix-xwayland-drags
#    match:class = ^$
#    match:title = ^$
#    match:xwayland = true
#    match:float = true
#    match:fullscreen = false
#    match:pin = false
#    no_focus = true
#}

#loupe tweaks
windowrule = match:class ^(org.gnome.Loupe)$, float on
windowrule = match:class ^(org.gnome.Loupe)$, size 1440 1000
windowrule = match:class ^(org.gnome.Loupe)$, center on

#dragon tweaks
windowrule = match:class ^(dragon)$, float on
windowrule = match:class ^(dragon)$, center on

#xdg portal rule
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, center on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, size 760 760

#vlc tweaks
windowrule = match:class ^(vlc)$, float on
windowrule = match:title (VLC media player), center on

#No opacity
windowrule = match:class ^(firefox)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(kitty)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(Spotify)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(steam)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(gimp)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(org.gnome.Loupe)$, opacity 1.0 override 1.0 override
windowrule = match:class ^(vlc)$, opacity 1.0 override 1.0 override

#Rule to blur quickshell bar and popups
layerrule = blur on, ignore_alpha 0.1, match:namespace bar
layerrule = blur on, ignore_alpha 0.1, match:namespace calweaPopup
#Rule to blur rofi
layerrule = blur on, ignore_alpha 0.1, match:namespace rofi
